apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: sliit-lab-10
  name: sliit-lab-10
spec:
  ports:
    - port: 8090
      protocol: TCP
      targetPort: 8090
  selector:
    app: sliit-lab-10
status:
  loadBalancer: {}
